/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             4237,
                                             2512,
                                             "Create Tetrahedral Zone",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             NULL)
;  sourceZone_MLST_D1 = TecGUIListAdd(Dialog1Manager,
                                   258,
                                   283,
                                   3727,
                                   1961,
                       1,
                       sourceZone_MLST_D1_CB);

  compute_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                 258,
                                 2308,
                                 1282,
                                 141,
                    "&Compute",
                    compute_BTN_D1_CB);

  sourceZone_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                   258,
                                   116,
                    "Source Zone(s)");

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
